FROM python:3.9.0

ENV PYTHONDONTWRITEBYYECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r requirementsd.txt

COPY ./core /app

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


